export type Vehicle = {
  id: number;
  groupId: string;
  color: string;
  slug: string;
  vin: string | null;
  year: number;
  make: string;
  model: string;
  category: string;
  seats: number;
  transmission: string;
  pricePerDay: number;
  image: string;
  description: string;
  isActive: boolean;
};

export const vehicles: Vehicle[] = [
  {
    id: 1,
    groupId: 'ford-ecosport',
    color: 'Unknown',
    slug: 'ford-ecosport-2021-unit-1',
    vin: 'MAJ3S2FE2MC452614',
    year: 2021,
    make: 'Ford',
    model: 'Ecosport',
    category: 'SUV',
    seats: 5,
    transmission: 'Automatic',
    pricePerDay: 59,
    image: '/vehicles/ford-ecosport-2021.jpg',
    description: 'Compact SUV for everyday rentals.',
    isActive: true,
  },
  {
    id: 2,
    groupId: 'ford-ecosport',
    color: 'Gray',
    slug: 'ford-ecosport-gray-2021',
    vin: 'MAJ3S2FE4MC452615',
    year: 2021,
    make: 'Ford',
    model: 'Ecosport',
    category: 'SUV',
    seats: 5,
    transmission: 'Automatic',
    pricePerDay: 59,
    image: '/vehicles/gray-ecosport-2021.jpg',
    description: 'Gray Ford Ecosport 2021.',
    isActive: true,
  },
  {
    id: 3,
    groupId: 'ford-mustang-mach-e',
    color: 'White',
    slug: 'ford-mustang-mach-e-white-2022',
    vin: '3FMTK1RMXNMA14393',
    year: 2022,
    make: 'Ford',
    model: 'Mustang Mach-E',
    category: 'SUV',
    seats: 5,
    transmission: 'Automatic',
    pricePerDay: 109,
    image: '/vehicles/white-mach-e-2022.jpg',
    description: 'Electric SUV with modern styling and range.',
    isActive: true,
  },
  {
    id: 4,
    groupId: 'ford-ecosport',
    color: 'Blue',
    slug: 'ford-ecosport-blue-2021',
    vin: 'MAJ3S2FE6MC455418',
    year: 2021,
    make: 'Ford',
    model: 'Ecosport',
    category: 'SUV',
    seats: 5,
    transmission: 'Automatic',
    pricePerDay: 59,
    image: '/vehicles/blue-ecosport-2021.jpg',
    description: 'Blue Ford Ecosport 2021.',
    isActive: true,
  },
  {
    id: 5,
    groupId: 'ford-f150',
    color: 'Unknown',
    slug: 'ford-f150-2019',
    vin: '1FTEX1CB5KKD27540',
    year: 2019,
    make: 'Ford',
    model: 'F-150',
    category: 'Truck',
    seats: 5,
    transmission: 'Automatic',
    pricePerDay: 89,
    image: '/vehicles/ford-f150-2019.jpg',
    description: 'Reliable pickup truck for work or travel.',
    isActive: true,
  },
  {
    id: 6,
    groupId: 'volkswagen-jetta',
    color: 'Unknown',
    slug: 'volkswagen-jetta-2018',
    vin: '3VW2B7AJ3JM247320',
    year: 2018,
    make: 'Volkswagen',
    model: 'Jetta',
    category: 'Sedan',
    seats: 5,
    transmission: 'Automatic',
    pricePerDay: 49,
    image: '/vehicles/volkswagen-jetta-2018.jpg',
    description: 'Practical sedan with efficient everyday driving.',
    isActive: true,
  },
  {
    id: 7,
    groupId: 'ford-explorer',
    color: 'Unknown',
    slug: 'ford-explorer-2022',
    vin: '1FMSK7DHXNGA82342',
    year: 2022,
    make: 'Ford',
    model: 'Explorer',
    category: 'SUV',
    seats: 7,
    transmission: 'Automatic',
    pricePerDay: 89,
    image: '/vehicles/ford-explorer-2022.jpg',
    description: 'Spacious SUV for families and airport runs.',
    isActive: true,
  },
  {
    id: 8,
    groupId: 'ford-expedition-max',
    color: 'Unknown',
    slug: 'ford-expedition-max-2022',
    vin: '1FMJK1HT8NEA09084',
    year: 2022,
    make: 'Ford',
    model: 'Expedition Max',
    category: 'SUV',
    seats: 8,
    transmission: 'Automatic',
    pricePerDay: 139,
    image: '/vehicles/ford-expedition-max-2022.jpg',
    description: 'Large full-size SUV with extra cargo space.',
    isActive: true,
  },
  {
    id: 9,
    groupId: 'chevy-malibu',
    color: 'White',
    slug: 'chevy-malibu-white-2023',
    vin: '1G1ZD5ST4PF132467',
    year: 2023,
    make: 'Chevrolet',
    model: 'Malibu',
    category: 'Sedan',
    seats: 5,
    transmission: 'Automatic',
    pricePerDay: 59,
    image: '/vehicles/chevy-malibu-white-2023.jpg',
    description: 'Comfortable midsize sedan in white.',
    isActive: true,
  },
  {
    id: 10,
    groupId: 'tesla-model-3',
    color: 'Black',
    slug: 'tesla-model-3-black-2018',
    vin: '5YJ3E1EA3JF123199',
    year: 2018,
    make: 'Tesla',
    model: 'Model 3',
    category: 'Sedan',
    seats: 5,
    transmission: 'Automatic',
    pricePerDay: 89,
    image: '/vehicles/tesla-model-3-black-2018.jpg',
    description: 'Electric sedan with premium tech feel.',
    isActive: true,
  },
  {
    id: 11,
    groupId: 'chevy-trax',
    color: 'Unknown',
    slug: 'chevy-trax-2021',
    vin: 'KL7CJLSM5MB377362',
    year: 2021,
    make: 'Chevrolet',
    model: 'Trax',
    category: 'SUV',
    seats: 5,
    transmission: 'Automatic',
    pricePerDay: 55,
    image: '/vehicles/chevy-trax-2021.jpg',
    description: 'Compact crossover for local and city trips.',
    isActive: true,
  },
  {
    id: 12,
    groupId: 'ford-ecosport',
    color: 'Red',
    slug: 'ford-ecosport-red-2019',
    vin: 'MAJ3S2GE1KC272262',
    year: 2019,
    make: 'Ford',
    model: 'Ecosport',
    category: 'SUV',
    seats: 5,
    transmission: 'Automatic',
    pricePerDay: 55,
    image: '/vehicles/ford-ecosport-red-2019.jpg',
    description: 'Red Ford Ecosport 2019.',
    isActive: true,
  },
  {
    id: 13,
    groupId: 'toyota-sienna',
    color: 'Unknown',
    slug: 'toyota-sienna-se-2017',
    vin: '5TDXZ3DC0HS888445',
    year: 2017,
    make: 'Toyota',
    model: 'Sienna SE',
    category: 'Minivan',
    seats: 7,
    transmission: 'Automatic',
    pricePerDay: 99,
    image: '/vehicles/toyota-sienna-se-2017.jpg',
    description: 'Spacious minivan ideal for family travel.',
    isActive: true,
  },
  {
    id: 14,
    groupId: 'ford-ecosport',
    color: 'Silver',
    slug: 'ford-ecosport-silver-2021',
    vin: 'MAJ3S2GE4MC409262',
    year: 2021,
    make: 'Ford',
    model: 'Ecosport',
    category: 'SUV',
    seats: 5,
    transmission: 'Automatic',
    pricePerDay: 59,
    image: '/vehicles/ford-ecosport-silver-2021.jpg',
    description: 'Silver Ford Ecosport 2021.',
    isActive: true,
  },
  {
    id: 15,
    groupId: 'ford-ecosport',
    color: 'Black',
    slug: 'ford-ecosport-black-2021',
    vin: 'MAJ3S2FE9MC419139',
    year: 2021,
    make: 'Ford',
    model: 'Ecosport',
    category: 'SUV',
    seats: 5,
    transmission: 'Automatic',
    pricePerDay: 59,
    image: '/vehicles/ford-ecosport-black-2021.jpg',
    description: 'Black Ford Ecosport 2021.',
    isActive: true,
  },
  {
    id: 16,
    groupId: 'ford-expedition-max',
    color: 'Unknown',
    slug: 'ford-expedition-max-2018',
    vin: '1FMJK1KT4JEA64294',
    year: 2018,
    make: 'Ford',
    model: 'Expedition Max',
    category: 'SUV',
    seats: 8,
    transmission: 'Automatic',
    pricePerDay: 129,
    image: '/vehicles/ford-expedition-max-2018.jpg',
    description: 'Large SUV with room for passengers and luggage.',
    isActive: true,
  },
  {
    id: 17,
    groupId: 'ford-ecosport',
    color: 'White',
    slug: 'ford-ecosport-white-2020',
    vin: 'MAJ3S2FE5LC371489',
    year: 2020,
    make: 'Ford',
    model: 'Ecosport',
    category: 'SUV',
    seats: 5,
    transmission: 'Automatic',
    pricePerDay: 55,
    image: '/vehicles/ford-ecosport-white-2020.jpg',
    description: 'White Ford Ecosport 2020.',
    isActive: true,
  },
  {
    id: 18,
    groupId: 'ford-ecosport',
    color: 'Tinted',
    slug: 'ford-ecosport-tinted-2021',
    vin: 'MAJ3S2FE5MC400863',
    year: 2021,
    make: 'Ford',
    model: 'Ecosport',
    category: 'SUV',
    seats: 5,
    transmission: 'Automatic',
    pricePerDay: 59,
    image: '/vehicles/ford-ecosport-tinted-2021.jpg',
    description: 'Tinted Ford Ecosport 2021.',
    isActive: true,
  },
  {
    id: 19,
    groupId: 'chevy-trax',
    color: 'Red',
    slug: 'chevy-trax-red-2024',
    vin: 'KL77LFE2XRC094495',
    year: 2024,
    make: 'Chevrolet',
    model: 'Trax',
    category: 'SUV',
    seats: 5,
    transmission: 'Automatic',
    pricePerDay: 69,
    image: '/vehicles/chevy-trax-red-2024.jpg',
    description: 'Red Chevy Trax 2024.',
    isActive: true,
  },
  {
    id: 20,
    groupId: 'chevy-trax',
    color: 'White',
    slug: 'chevy-trax-white-2024',
    vin: 'KL77LHE26RC059898',
    year: 2024,
    make: 'Chevrolet',
    model: 'Trax',
    category: 'SUV',
    seats: 5,
    transmission: 'Automatic',
    pricePerDay: 69,
    image: '/vehicles/chevy-trax-white-2024.jpg',
    description: 'White Chevy Trax 2024.',
    isActive: true,
  },
  {
    id: 21,
    groupId: 'chevy-malibu',
    color: 'Unknown',
    slug: 'chevy-malibu-2023',
    vin: '1G1ZD5ST0PF201039',
    year: 2023,
    make: 'Chevrolet',
    model: 'Malibu',
    category: 'Sedan',
    seats: 5,
    transmission: 'Automatic',
    pricePerDay: 59,
    image: '/vehicles/chevy-malibu-2023.jpg',
    description: 'Midsize sedan with comfortable ride quality.',
    isActive: true,
  },
  {
    id: 22,
    groupId: 'porsche-911-gt3',
    color: 'Unknown',
    slug: 'porsche-911-gt3-2015',
    vin: 'WP0AC2A91FS184219',
    year: 2015,
    make: 'Porsche',
    model: '911 GT3',
    category: 'Sports Car',
    seats: 2,
    transmission: 'Automatic',
    pricePerDay: 299,
    image: '/vehicles/porsche-911-gt3-2015.jpg',
    description: 'High-performance sports car for premium rentals.',
    isActive: true,
  },
  {
    id: 23,
    groupId: 'tesla-cybertruck',
    color: 'Unknown',
    slug: 'tesla-cybertruck-2024',
    vin: '7G2CEHEDXRA042726',
    year: 2024,
    make: 'Tesla',
    model: 'Cybertruck',
    category: 'Truck',
    seats: 5,
    transmission: 'Automatic',
    pricePerDay: 249,
    image: '/vehicles/tesla-cybertruck-2024.jpg',
    description: 'Electric pickup with bold styling and utility.',
    isActive: true,
  },
];